### ISSUE TITLE
source code rearrangement to remove HW dependencies

### ISSUE THREAD

**Issue by twister2016** [twister2016/twister#35]
Make source code rearrangement to remove HW dependencies, and rebuild into a new twister package in github.
This task should remove ALL dependencies on Dell or any hardware, and be able to run on AWS. The intention is that the new package can run on other public clouds too in future, such as Google, MSFT, rackspace etc. But NO implementation is needed in this task -- only design considerations as appropriate.

**Comment by wriaz** [comment]
All Dell specific dependencies removed from the source code.
