### ISSUE TITLE
arp core dumps

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#52]
% ./ARP 
core dumps.
% sudo ./ARP works

1) ./ARP should not core dump but prints out what linux normally say when it requires root permission, and suggest to the user to run as sudo. Look for linux for example of wording.
2) Question, is there a way to avoid sudo? arp command in linux does not need root permission. this is optional if impossible or difficult.

I didnt check all examples, but if they have the same problem, all need the same fix.

**Comment by chaudhryusama** [comment]
1) is solved by the following commit
https://github.com/twister2016/twister/commit/57185b4f9b30ba5b14b073b856e536ff2b9b4e7c

2) Linux added a patch to prevent normal user from using memory. However, sudo can be avoided by running the application with no-huge flag but it will cost in perforamce

**Comment by wenjing** [comment]
Understood. It's OK to use consistent library and always sudo for all twister commands.
