### ISSUE TITLE
Debug information in commands

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#62]
All twister commands print out debug information in the beginning:
EAL xxxxxxx
PMD xxxxxxx

All commands should by default not print these lines of EAL and PMD debug information. Add "-debug" option to all commands. When debug flag is set, then print these lines.

**Comment by wriaz** [comment]
Following commit resolves the issue
https://github.com/twister2016/twister/commit/cd0e4bdd52fc51bf9f069b59dbb24103e7dc8eeb

Debug information can still be seen by running applications with "-d" flag
