### ISSUE TITLE
twiperf "total datagrams" column always zero

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#63]
The "total datagram" column seems always 0.
If it is not implemented, remove it. If it is implemented, then there is a bug.

**Comment by chaudhryusama** [comment]
This issue has been addressed in the following commit
https://github.com/twister2016/twister/commit/f0d311d98d3520656df8649dc43dc34ed880c45c

**Comment by wriaz** [comment]
Verified, issue is resolved now
