### ISSUE TITLE
twiperf improvements

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#65]
1) twiperf -c does not print anything. I think it should print too (similar to iperf -c).
2) RX and TX columns should be RX pkts/s, TX pkts/s.
3) Packet size is not shown. 
4) We should add an option to specify packet size in bytes.
5) default packet size should be 1024? or 1500? Let's choose the same as iperf's default packet size.
6) FOr UDP, it should report latency in ms as well.

**Comment by chaudhryusama** [comment]
For 1) twiperf -c will start printing after it is connected to the host. Once connected, it will print too.
For 2) It is done in the below commit
https://github.com/twister2016/twister/commit/fa918a6bbd889518ed72eaf949f9770afee2a4aa
For 3) It is done in the below commit
https://github.com/twister2016/twister/commit/fa918a6bbd889518ed72eaf949f9770afee2a4aa
For 4) the option is there, the user has to specify the packet size by argument -n or --bytes. 
For 5) the default size is 1500 in iperf. The default size for twiperf is also changed from 64 to 1500 bytes.

**Comment by wriaz** [comment]
1) is solved with resolution of #64 
2,3,4 and 5 were already resloved
6) latency in ms is also added in twiperf in below commit
https://github.com/twister2016/twister/commit/4323941d5f21ad72322c9ba6baf2a8921ac0f79c
