### ISSUE TITLE
twiperf unimplemented options?

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#66]
If I use twiperf -h, it prints out a list of options. Are all those options implemented? It does not seem to be. Either remove unimplemented options in Help, or implement them.

**Comment by wenjing** [comment]
"-h" the message does not seem all correct.
-P -B not sure if implemented.

**Comment by chaudhryusama** [comment]
Yes, they are not implemented. I have removed these extra options from printing in the below commit
https://github.com/twister2016/twister/commit/b2e95e0ccf58921d7ee0464a45b9240a5930740d

**Comment by wriaz** [comment]
Verified, -P -B are removed. Issue is resolved now
