### ISSUE TITLE
client sent/recv indicates huge loss... and long latency

### ISSUE THREAD

**Issue by wenjing** [twister2016/twister#71]
Connecting to host 10.0.2.110, port 5001
local 10.0.2.63, port 7777 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Connected to 10.0.2.110 port 5001
Packet Size: 1500 bytes
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interval(sec)    RX pkts/s    TX pkts/s      Bandwidth (Mbits/s)   Datagrams Sent   Datagrams Recvd        Latency      Jitter/sec
  0.00-1.00          75722       817823       10225.82                   10600512             75722        2525 μs        16 μs
  1.00-2.00          75001       817600       10215.00                   21224766            150723        2537 μs        16 μs
  2.00-3.00          75003       817824       10217.59                   31844928            225726        2539 μs        16 μs
  3.00-4.00          75004       817632       10215.41                   42458283            300730        2545 μs        17 μs
  4.00-5.00          75003       817632       10215.39                   53073761            375733        2544 μs        17 μs
  5.00-6.00          75001       817600       10215.00                   63689052            450734        2550 μs        17 μs
  6.00-7.00          75001       817216       10210.61                   74280161            525735        2542 μs        19 μs

Per Slack discussion, we think this is caused by sending too much traffic by the source (currently it's entirely based on port spec, and that's not a good choice in AWS or heavily shared network). To correct it, we will implement an option to specify packet size and another to specify packet rate. The default (if the user does not use these option) is to send based on port bandwidth spec.

**Comment by wenjing** [comment]
Note also: even with rate specified, a burst can still generate latency (buffering) or loss (if burst is bigger than buffer). twiperf should use an appropriate burst size so that it is smaller than the buffer size.

**Comment by wriaz** [comment]
Resolved by adding a bandwidth flag. Run the twiperf client with `-b` flag to specify packet rate and `-n` flag to specify packet size e.g. `sudo twiperf -n 64 -c <server ip> -b 75000`
Flags can also be viewed with `sudo twiperf help` command
Fix added in following commit.
https://github.com/twister2016/twister/commit/185fef75f32982ea3648d7d6aa7c9a72895c323a
