### ISSUE TITLE
twifconfig should enforce gateway to be from the same network

### ISSUE THREAD

**Issue by wriaz** [twister2016/twister#75]
`twifconfig` allows user to provide ip address and subnet mask and uses the first address of that network as the gateway address. However if user specifies a gateway address, it configures user specified network. `twifconfig` should also enforce that if specified gateway is out of range of network, it should throw an error instead of setting it. e.g
```
[ec2-user@ip-10-0-1-244 ~]$ sudo twifconfig  tw0 10.4.5.222/26 101.4.0.1
101.4.0.1 10.4.5.222 255.255.255.192
tw0        inet addr: 10.4.5.222 Mask: 255.255.255.192 Gateway: 101.4.0.1
           Status: UP HWaddr
```

**Comment by moeedkhalid** [comment]
resolved by 6bdf4db85e4ed30786e04064c0fe3f0720285d01
